config/routes.rb
Rails.application.routes.draw do
  resources :fees
  resources :payments
  resources :subscriptions
  resources :prices
  resources :activities
  root 'clients#index';

  resources :users
  resources :clients
  resources :teachers
  resource :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :activity
  belongs_to :client
  has_many :payments, dependent: :destroy

  validates :initial_date, presence: true

  def can_access
    subscription = Subscription.where(
':today BETWEEN initial_date AND end_date AND activity_id = :activity_id AND client_id = :client_id', {
today: Date.today, activity_id: activity_id, client_id: client_id }).first

    if subscription && payed
      true
    else
      false
    end
  end

  scope :current_subscription, lambda {where(initial_date: Time.now.beginning_of_month..(Time.now.end_of_month))}
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: %i[ show edit update destroy ]

  # GET /subscriptions or /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1 or /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions or /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        @subscription.end_date = @subscription.initial_date.end_of_month
        @subscription.price = @subscription.activity.price.amount
        @subscription.save
        format.html { redirect_to @subscription.client, notice: "La cuota ha sido creada." }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1 or /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        @subscription.end_date = @subscription.initial_date.end_of_month
        @subscription.save
        format.html { redirect_to @subscription.client, notice: "La cuota ha sido editada." }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to @subscription.client, notice: "La cuota ha sido borrada." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:initial_date, :end_date, :price, :payed, :activity_id, :client_id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= simple_form_for(@subscription) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="mb-3">
      <%= f.input :initial_date, label: 'Mes' , discard_day: true, discard_year: true %>
    </div>

    <div class="mb-3">
      <%= f.association :activity, label_method: :to_label, prompt: "Selecciona una actividad" %>
    </div>

    <div class="mb-3">
      <%= f.association :client, prompt: "Selecciona un cliente" %>
    </div>

    <div class="mb-3">
      <%= f.input :price %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
    <%= link_to 'Atras', @subscription.client, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<% content_for :heading, 'Editar Cuota'%>

<%= render 'form', subscription: @subscription %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Initial date</th>
      <th>End date</th>
      <th>Price</th>
      <th>Payed</th>
      <th>Activity</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.initial_date %></td>
        <td><%= subscription.end_date %></td>
        <td><%= subscription.price %></td>
        <td><%= subscription.payed %></td>
        <td><%= subscription.activity_id %></td>
        <td><%= subscription.client_id %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>Nueva Cuota</h1>

<%= render 'form', subscription: @subscription %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Initial date:</strong>
  <%= @subscription.initial_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @subscription.end_date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @subscription.price %>
</p>

<p>
  <strong>Payed:</strong>
  <%= @subscription.payed %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @subscription.activity_id %>
</p>

<p>
  <strong>Client:</strong>
  <%= @subscription.client_id %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>