config/routes.rb
Rails.application.routes.draw do
  resources :fees
  resources :payments
  resources :subscriptions
  resources :prices
  resources :activities
  root 'clients#index';

  resources :users
  resources :clients
  resources :teachers
  resource :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :subscription
  has_one :payment

  scope :current_fee, lambda {where(initial_date: Time.now.beginning_of_month..(Time.now.end_of_month))}
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
  before_action :set_fee, only: %i[ show edit update destroy ]

  # GET /fees or /fees.json
  def index
    @fees = Fee.all
  end

  # GET /fees/1 or /fees/1.json
  def show
  end

  # GET /fees/new
  def new
    @fee = Fee.new
  end

  # GET /fees/1/edit
  def edit
  end

  # POST /fees or /fees.json
  def create
    @fee = Fee.new(fee_params)

    respond_to do |format|
      if @fee.save
        @fee.initial_date = Date.new
        @fee.end_date = @fee.initial_date.end_of_month
        @fee.price = @fee.subscription.activity.price.amount
        @fee.payed = true
        @payment = Payment.create(amount: @fee.price, fee: @fee)

        @fee.save
        format.html { redirect_to @fee, notice: "Fee was successfully created." }
        format.json { render :show, status: :created, location: @fee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fees/1 or /fees/1.json
  def update
    respond_to do |format|
      if @fee.update(fee_params)
        format.html { redirect_to @fee, notice: "Fee was successfully updated." }
        format.json { render :show, status: :ok, location: @fee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fees/1 or /fees/1.json
  def destroy
    @fee.destroy
    respond_to do |format|
      format.html { redirect_to fees_url, notice: "Fee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fee
      @fee = Fee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fee_params
      params.require(:fee).permit(:initial_date, :end_date, :payed, :subscriptions_id)
    end
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/views/fees/_form.html.erb
<%= simple_form_for(@fee) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :initial_date %>
    <%= f.input :end_date %>
    <%= f.input :payed %>
    <%= f.association :subscriptions %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fees/edit.html.erb
<h1>Editing Fee</h1>

<%= render 'form', fee: @fee %>

<%= link_to 'Show', @fee %> |
<%= link_to 'Back', fees_path %>

app/views/fees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fees</h1>

<table>
  <thead>
    <tr>
      <th>Initial date</th>
      <th>End date</th>
      <th>Payed</th>
      <th>Subscriptions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fees.each do |fee| %>
      <tr>
        <td><%= fee.initial_date %></td>
        <td><%= fee.end_date %></td>
        <td><%= fee.payed %></td>
        <td><%= fee.subscriptions_id %></td>
        <td><%= link_to 'Show', fee %></td>
        <td><%= link_to 'Edit', edit_fee_path(fee) %></td>
        <td><%= link_to 'Destroy', fee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fee', new_fee_path %>

app/views/fees/new.html.erb
<h1>New Fee</h1>

<%= render 'form', fee: @fee %>

<%= link_to 'Back', fees_path %>

app/views/fees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Initial date:</strong>
  <%= @fee.initial_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @fee.end_date %>
</p>

<p>
  <strong>Payed:</strong>
  <%= @fee.payed %>
</p>

<p>
  <strong>Subscriptions:</strong>
  <%= @fee.subscriptions_id %>
</p>

<%= link_to 'Edit', edit_fee_path(@fee) %> |
<%= link_to 'Back', fees_path %>