config/routes.rb
Rails.application.routes.draw do
  resources :fees
  resources :payments
  resources :subscriptions
  resources :prices
  resources :activities
  root 'clients#index';

  resources :users
  resources :clients
  resources :teachers
  resource :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_one :price, dependent: :destroy
  accepts_nested_attributes_for :price, allow_destroy: true

  validates :name, presence: true

  def to_label
    "#{name} / #{ price.amount}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
require 'barby/barcode/code_128'
require 'barby/barcode'
require 'barby/outputter/cairo_outputter'

class Client < ApplicationRecord
  has_many :subscriptions, dependent: :destroy
  has_one_attached :medic_file, dependent: :destroy

  validates :first_name, :last_name, :dni, :birthday, :phone_number, :email, presence: true
  validates :dni, uniqueness: true

  def to_s
    "#{first_name} #{last_name}"
  end

  def can_access
    current_subscription = subscriptions.current_subscription

    if current_subscription.empty?
      return false
    end

    current_subscription.first.payed
  end

  def activities
    @subscriptions = Subscription.where(client_id: id).eager_load(:activity).group_by(&:activity_id)
  end

  def get_barcode
    barcode = Barby::Code128B.new(dni)
    outputter = Barby::CairoOutputter.new(barcode)
    outputter.height = 90
    outputter.xdim = 2

    Base64.encode64(outputter.to_png)
  end
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :subscription
  has_one :payment

  scope :current_fee, lambda {where(initial_date: Time.now.beginning_of_month..(Time.now.end_of_month))}
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :subscription

  validates :amount, presence: true, numericality: true
end

app/models/price.rb
class Price < ApplicationRecord
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :activity
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :activity
  belongs_to :client
  has_many :payments, dependent: :destroy

  validates :initial_date, presence: true

  def can_access
    subscription = Subscription.where(
':today BETWEEN initial_date AND end_date AND activity_id = :activity_id AND client_id = :client_id', {
today: Date.today, activity_id: activity_id, client_id: client_id }).first

    if subscription && payed
      true
    else
      false
    end
  end

  scope :current_subscription, lambda {where(initial_date: Time.now.beginning_of_month..(Time.now.end_of_month))}
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  validates :first_name, :last_name, :dni, :birthday, :phone_number, presence: true
  validates :dni, uniqueness: true

  def to_label
    "#{first_name} #{last_name} / #{dni}"
  end

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :teacher

  has_secure_password

  validates :email, :teacher_id, presence: true
  validates :email, uniqueness: true
  validates :teacher_id, uniqueness: true

  def to_s
    teacher.to_s
  end
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
  before_action :set_fee, only: %i[ show edit update destroy ]

  # GET /fees or /fees.json
  def index
    @fees = Fee.all
  end

  # GET /fees/1 or /fees/1.json
  def show
  end

  # GET /fees/new
  def new
    @fee = Fee.new
  end

  # GET /fees/1/edit
  def edit
  end

  # POST /fees or /fees.json
  def create
    @fee = Fee.new(fee_params)

    respond_to do |format|
      if @fee.save
        @fee.initial_date = Date.new
        @fee.end_date = @fee.initial_date.end_of_month
        @fee.price = @fee.subscription.activity.price.amount
        @fee.payed = true
        @payment = Payment.create(amount: @fee.price, fee: @fee)

        @fee.save
        format.html { redirect_to @fee, notice: "Fee was successfully created." }
        format.json { render :show, status: :created, location: @fee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fees/1 or /fees/1.json
  def update
    respond_to do |format|
      if @fee.update(fee_params)
        format.html { redirect_to @fee, notice: "Fee was successfully updated." }
        format.json { render :show, status: :ok, location: @fee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fees/1 or /fees/1.json
  def destroy
    @fee.destroy
    respond_to do |format|
      format.html { redirect_to fees_url, notice: "Fee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fee
      @fee = Fee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fee_params
      params.require(:fee).permit(:initial_date, :end_date, :payed, :subscriptions_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_signin

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "El usuario ha sido creado." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "El usuario ha sido editado." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "El usuario ha sido borrado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :teacher_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="#">Gym</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if current_user %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="usuarios" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Usuarios
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "Ver todos", users_path, class: "dropdown-item" %>
                <li><%= link_to "Nuevo", new_user_path, class: "dropdown-item" %>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="profesores" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Profesores
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "Ver todos", teachers_path, class: "dropdown-item" %>
                <li><%= link_to "Nuevo", new_teacher_path, class: "dropdown-item" %>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="clientes" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Clientes
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "Ver todos", clients_path, class: "dropdown-item" %>
                <li><%= link_to "Nuevo", new_client_path, class: "dropdown-item" %>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="actividades" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Actividades
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "Ver todos", activities_path, class: "dropdown-item" %>
                <li><%= link_to "Nuevo", new_activity_path, class: "dropdown-item" %>
              </ul>
            </li>
          <% end %>
        </ul>

        <ul class="navbar-nav mb-2 mb-lg-0">
          <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="usuario" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.to_s %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "Cerrar Sesión",  sessions_path, method: :delete, class: "dropdown-item" %>
            </ul>
          </li>
          <% else %>
            <%= link_to "Iniciar Sesión", new_sessions_path, class: "dropdown-item" %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GymErp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="/css/styles.css" rel="stylesheet">
    <script src="/js/javascript.js"></script>
  </head>

  <body>
    <%= render "layouts/header" %>

    <% if flash[:alert] %>
      <div class="alert alert-danger mt-3">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <% if flash[:notice] %>
      <div class="alert alert-primary mt-3">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <main class="container">
      <div class="card mt-3">
        <div class="card-header"><%= yield :heading %></div>
        <div class="card-body">
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>